In [2]:
import numpy as np

A=np.array([[56.0,0.0,4.4,68.0],
            [1.2,104.0,52.0,8.0],
            [1.8,135.0,99.0,0.9]
])

print(A)

cal=A.sum(axis=0) #sum vertically
print(cal)

percentage=100*A/cal.reshape(1,4) #reshape called just to make sure of the dimensions
print(percentage)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]
[ 59.  239.  155.4  76.9]
[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [3]:
np.array([[1,2,3],[4,5,6]])+np.array([100,200,300])

array([[101, 202, 303],
       [104, 205, 306]])

In [4]:
np.array([[1,2,3],[4,5,6]])+np.array([[100],[200]])

array([[101, 102, 103],
       [204, 205, 206]])

In [6]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c)

[[-0.55753932  0.01806077  0.99743223]
 [ 0.9988742  -0.18593603 -0.17116469]
 [ 0.63327102 -0.57113503  0.76855786]]
